name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-versions.outputs.result }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v5
      - name: Get dependency versions
        uses: mikefarah/yq@v4.45.4
        id: get-versions
        with:
          cmd: yq eval -o=json -I=0 versions.yaml

  build_and_push:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      # Prevent a failure in one image from stopping the other builds
      fail-fast: false
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine version change
        id: changed-version
        run: |
          BASE=${{ github.event_name == 'pull_request' && format('origin/{0}', github.base_ref) || 'HEAD~1' }}
          CHANGED_FILES=$(git diff --name-only $BASE...HEAD)
          echo $CHANGED_FILES
          # Looking for:
          # versions.yaml
          # Dockerfile
          if echo "$CHANGED_FILES" | grep -q -e "^versions.yaml$" -e "^Dockerfile$"; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Determine image push
        uses: actions/github-script@v7
        id: should-release
        with:
          script: |
            if (context.eventName == "pull_request") return false;
            if (context.eventName == "workflow_dispatch") return true;
            return "${{ steps.changed-version.outputs.any_changed }}" == "true";

      - name: Set major postgres version
        id: version
        run: |
          pg_major=$(echo ${{ matrix.cdpg }} | cut -d'.' -f1 | cut -d'-' -f2)
          echo "pg_major=$pg_major" >> "$GITHUB_OUTPUT"

      - name: Generate docker image tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          flavor: |
            # Disable latest tag
            latest=false
          images: |
            name=ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.cdpg }}-${{ matrix.vectorchord }},enable=${{ steps.should-release.outputs.result }}

      - name: Generate docker image tags (migrate)
        id: metadata-migrate
        uses: docker/metadata-action@v5
        with:
          flavor: |
            # Disable latest tag
            latest=false
          images: |
            name=ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.cdpg }}-${{ matrix.vectorchord }}-migrate-${{ matrix.pgvectors }},enable=${{ steps.should-release.outputs.result }}

      - name: Build and push image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ !github.event.pull_request.head.repo.fork && steps.metadata.outputs.tags != '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            CRUNCHYDATA_VERSION=${{ matrix.cdpg }}
            VECTORCHORD_VERSION=${{ matrix.vectorchord }}
            PG_MAJOR=${{ steps.version.outputs.pg_major }}

      - name: Build and push image (migrate)
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: Dockerfile.migrate
          platforms: linux/amd64,linux/arm64
          push: ${{ !github.event.pull_request.head.repo.fork && steps.metadata-migrate.outputs.tags != '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.metadata-migrate.outputs.tags }}
          labels: ${{ steps.metadata-migrate.outputs.labels }}
          build-args: |
            CRUNCHYDATA_VERSION=${{ matrix.cdpg }}
            PGVECTORS_VERSION=${{ matrix.pgvectors }}
            VECTORCHORD_VERSION=${{ matrix.vectorchord }}
            PG_MAJOR=${{ steps.version.outputs.pg_major }}

  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build results
    needs: [build_and_push]
    steps:
      - run: |
          result="${{ needs.build_and_push.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
